import Head from "next/head";
import { useRouter } from 'next/router'
import { useState } from "react";
import FightCollapser from "~/components/FightCollapser";
import { getParamsFromUrl } from "~/server/utils";

import { api } from "~/utils/api";
import { msToDuration } from "~/utils/log-utils";

export default function Home() {
  const [logUrl, setLogUrl] = useState("");
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Mitty</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <form className="relative w-3/5" 
            onSubmit={(event) => {
              event.preventDefault();
              const urlParams = getParamsFromUrl(logUrl);
              if (urlParams.isValid) router.push(`/${urlParams.reportCode}/${urlParams.fightId}`)
            }}
          >
            <div>
              <input 
                type="text" 
                name="logUrl"
                className="input input-bordered w-full" 
                placeholder="FFLogs URL" 
                value={logUrl}
                onChange={(e) => setLogUrl(e.target.value)}
                required
              />
              <button type="submit" className="btn btn-primary btn-sm absolute end-2 bottom-2">Get Log</button>
            </div>
          </form>
        </div>
      </main>
    </>
  );
}
