import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

import { api } from "~/utils/api";

export default function Home() {
  const [logUrl, setLogUrl] = useState("");
  const logData = api.post.getLogData.useQuery({logUrl: logUrl}, {enabled: false});

  return (
    <>
      <Head>
        <title>Mit Checker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <form className="relative w-3/5" 
            onSubmit={(event) => {
              event.preventDefault();
              logData.refetch();
            }}
          >
            <div>
              <input 
                type="text" 
                name="logUrl"
                className="block w-full p-4 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" 
                placeholder="FFLogs URL" 
                value={logUrl}
                onChange={(e) => setLogUrl(e.target.value)}
                required
              />
              <button type="submit" className="text-white absolute end-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Get Log</button>
            </div>
          </form>
          <p className="text-2xl text-white">
            {logData.data ? logData.data.url : "Loading..."}
          </p>
          <p className="text-l text-white">
            {logData.data?.fightData ? JSON.stringify(logData.data.fightData) : "Loading..."}
          </p>
        </div>
      </main>
    </>
  );
}
